//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class city_bd
    {
        public decimal city_id { get; set; }
        public string city_name { get; set; }
        public string city_code { get; set; }
        public decimal city_state { get; set; }
        public decimal city_country_id { get; set; }
        public string city_desc { get; set; }
        public string city_general_conditions { get; set; }
        public decimal is_pickup { get; set; }
        public decimal is_delivery { get; set; }
    }
}
