//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class country_bd
    {
        public decimal country_id { get; set; }
        public string country_Name { get; set; }
        public string country_code { get; set; }
        public decimal country_state { get; set; }
        public string country_desc { get; set; }
        public string country_general_coditions { get; set; }
    }
}
