//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class definition
    {
        public decimal id { get; set; }
        public string def_name { get; set; }
        public decimal def_state { get; set; }
        public string def_desc { get; set; }
        public string scode { get; set; }
    }
}
