//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class masmix_dbEntities : DbContext
    {
        public masmix_dbEntities()
            : base("name=masmix_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<city_bd> city_bd { get; set; }
        public virtual DbSet<country_bd> country_bd { get; set; }
        public virtual DbSet<definition> definitions { get; set; }
        public virtual DbSet<route_bd> route_bd { get; set; }
        public virtual DbSet<service_bd> service_bd { get; set; }
        public virtual DbSet<wharehouse_bd> wharehouse_bd { get; set; }
        public virtual DbSet<routes_of_services> routes_of_services { get; set; }
        public virtual DbSet<services_of_cities> services_of_cities { get; set; }
        public virtual DbSet<shipments_of_services> shipments_of_services { get; set; }
    }
}
