//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class route_bd
    {
        public decimal route_id { get; set; }
        public string route_name { get; set; }
        public decimal route_from_country { get; set; }
        public decimal route_from_city { get; set; }
        public decimal route_to_country { get; set; }
        public decimal route_to_city { get; set; }
        public decimal route_state { get; set; }
    }
}
