//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class routes_of_services
    {
        public decimal ser { get; set; }
        public decimal service_id { get; set; }
        public decimal route_id { get; set; }
    }
}
