//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Release_1
{
    using System;
    using System.Collections.Generic;
    
    public partial class wharehouse_bd
    {
        public decimal wharehouse_id { get; set; }
        public string wharehouse_name { get; set; }
        public decimal wharehouse_state { get; set; }
        public decimal wharehouse_country_id { get; set; }
        public decimal wharehouse_city_id { get; set; }
        public string wharehouse_size_desc { get; set; }
        public decimal wharehouse_width_ft { get; set; }
        public decimal wharehouse_width_cm { get; set; }
        public decimal wharehouse_length_ft { get; set; }
        public decimal wharehouse_length_cm { get; set; }
        public decimal wharehouse_hieght_ft { get; set; }
        public decimal wharehouse_hieght_cm { get; set; }
        public string wharehouse_address { get; set; }
        public string wharehouse_tel1 { get; set; }
        public string wharehouse_tel2 { get; set; }
        public decimal is_office_delivery { get; set; }
        public decimal is_warehouse { get; set; }
        public string time_from { get; set; }
        public string time_to { get; set; }
        public string day_off { get; set; }
    }
}
